language: objective-c
osx_image: xcode8.2
before_install:
  - gem install fastlane --no-doc
script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - fastlane scan
  # - pod lib lint
